[PHP]
extension_dir = "C:\Users\mgpde\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.3_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"
extension=curl
extension=fileinfo
extension=mbstring
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=zip
extension=mysqli

; Basic settings to ensure Laravel runs smoothly
memory_limit = 512M
upload_max_filesize = 100M
post_max_size = 100M
max_execution_time = 300
date.timezone = UTC